language: node_js

#cache:
#  yarn: true
#  directories:
#    - node_modules

notifications:
  email: false

node_js:
  - "9"

branches:
  only:
  - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=`yarn global bin`:$PATH
  - yarn global add greenkeeper-lockfile@2
  - yarn global add lerna

install:
  - lerna bootstrap
  - lerna ls

before_script:
  - greenkeeper-lockfile-update

script:
  - lerna run ci:build

after_script:
  - git branch
  - greenkeeper-lockfile-upload

after_success:
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
  - lerna run ci:coveralls --scope=webpack-bundle
  - lerna publish --conventional-commits --yes
  - git diff

git nches:
  except:
    - /^v\d+\.\d+\.\d+$/
