language: node_js

#cache:
#  yarn: true
#  directories:
#    - node_modules

notifications:
  email: false

node_js:
  - "9"

branches:
  only:
  - master

before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=`yarn global bin`:$PATH
  - yarn global add greenkeeper-lockfile@2
  - yarn global add lerna

install:
  - lerna bootstrap

before_script:
  - greenkeeper-lockfile-update

script:
  - lerna run ci:build

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - lerna run ci:coveralls --scope=webpack-bundle
  - lerna publish -m "bump versions [ci skip]" --conventional-commits --yes

git nches:
  except:
    - /^v\d+\.\d+\.\d+$/
