language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - "9"

branches:
  only:
    - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=`yarn global bin`:$PATH
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
  - yarn global add greenkeeper-lockfile@2
  - yarn global add lerna

install:
  - lerna bootstrap

before_script:
  - greenkeeper-lockfile-update
  - git checkout master
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git remote set-url origin https://${GH_TOKEN}@github.com/izatop/webpack-bundle.git

script:
  - lerna run ci:build
  - lerna publish --conventional-commits --yes

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - lerna run ci:coveralls --scope=webpack-bundle

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
