language: node_js

#cache:
#  yarn: true
#  directories:
#    - node_modules

notifications:
  email: false

node_js:
  - '10'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=`yarn global bin`:$PATH
  - yarn global add greenkeeper-lockfile@1
  - yarn global add lerna
  - yarn list

before_script:
  #- greenkeeper-lockfile-update
  - lerna bootstrap

script:
  - lerna run ci:build --scope=webpack-bundle

#after_script:
#  - greenkeeper-lockfile-upload

after_success:
  - lerna run ci:coveralls --scope=webpack-bundle
  - yarn lerna exec --concurrency 1 "npx --no-install semantic-release -e semantic-release-monorepo"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
