language: node_js

#cache:
#  yarn: true
#  directories:
#    - node_modules

notifications:
  email: false

node_js:
  - "9"

branches:
  only:
  - master

before_install:
  - greenkeeper-lockfile-update
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

install:
  - yarn --pure-lockfile

before_script:
  - git checkout master
  - lerna updated --json

script:
  - lerna run ci:build

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - lerna run ci:coveralls --scope=webpack-bundle
  - lerna publish -m "bump versions [ci skip]" --conventional-commits --yes

git nches:
  except:
    - /^v\d+\.\d+\.\d+$/
